const crypto = require("crypto");
const PdfKit = require("pdfkit");
const ExcelJS = require("exceljs");
const billModel = require("../models/billModel");
const userModel = require("../models/userModel");
const notificationModel = require("../models/notificationModel");
const { generateAnalytics } = require("../services/aiAssistantService");

function groupChargesByBillId(bills, charges) {
  const chargeMap = new Map();

  for (const charge of charges) {
    if (!chargeMap.has(charge.bill_id)) {
      chargeMap.set(charge.bill_id, []);
    }
    chargeMap.get(charge.bill_id).push(charge);
  }

  return bills.map((bill) => ({
    ...bill,
    charges: chargeMap.get(bill.id) || [],
  }));
}

function buildInvoicePayload(bill) {
  const invoiceDate = bill.created_at ? new Date(bill.created_at).toISOString() : new Date().toISOString();
  return {
    invoiceNumber: bill.invoice_number,
    invoiceDate,
    resident: {
      id: bill.resident_id,
      name: bill.resident_name,
      email: bill.resident_email,
    },
    bill: {
      id: bill.id,
      type: bill.bill_type,
      title: bill.title,
      billingMonth: bill.billing_month,
      dueDate: bill.due_date,
      status: bill.status,
      paymentStatus: bill.payment_status,
      totalAmount: Number(bill.total_amount || 0),
      paidAmount: Number(bill.paid_amount || 0),
      balanceAmount: Number(bill.total_amount || 0) - Number(bill.paid_amount || 0),
      lateFeeAmount: Number(bill.late_fee_amount || 0),
      charges: bill.charges || [],
    },
    paymentInfo: {
      gatewayProvider: bill.gateway_provider,
      gatewayOrderId: bill.gateway_order_id,
      gatewayPaymentId: bill.gateway_payment_id,
      upiReference: bill.upi_reference,
      paidAt: bill.paid_at,
    },
  };
}

function formatCurrency(amount) {
  return `INR ${Number(amount || 0).toFixed(2)}`;
}

function streamPdfResponse(res, filename, buildFn) {
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
  const doc = new PdfKit({ size: "A4", margin: 40 });
  doc.pipe(res);
  buildFn(doc);
  doc.end();
}

function buildInvoicePdf(doc, payload) {
  // Add NEXORA branding header
  doc.fontSize(16).fillColor("#14B8A6").text("NEXORA", { align: "center" });
  doc.fontSize(10).fillColor("gray").text("Smart Society Management Platform", { align: "center" });
  doc.moveDown();
  
  doc.fontSize(18).text("Invoice", { align: "center" });
  doc.moveDown();

  doc.fontSize(12).text(`Invoice Number: ${payload.invoiceNumber}`);
  doc.text(`Invoice Date: ${payload.invoiceDate}`);
  doc.text(`Status: ${payload.bill.status}`);
  doc.text(`Payment Status: ${payload.bill.paymentStatus}`);
  doc.moveDown();

  doc.fontSize(14).text("Resident Details", { underline: true });
  doc.fontSize(12).text(`Name: ${payload.resident.name}`);
  doc.text(`Email: ${payload.resident.email}`);
  doc.moveDown();

  doc.fontSize(14).text("Bill Summary", { underline: true });
  doc.fontSize(12).text(`Title: ${payload.bill.title}`);
  doc.text(`Billing Month: ${payload.bill.billingMonth || "N/A"}`);
  doc.text(`Due Date: ${payload.bill.dueDate || "N/A"}`);
  doc.text(`Total Amount: ${formatCurrency(payload.bill.totalAmount)}`);
  doc.text(`Paid Amount: ${formatCurrency(payload.bill.paidAmount)}`);
  doc.text(`Balance Amount: ${formatCurrency(payload.bill.balanceAmount)}`);
  doc.text(`Late Fee: ${formatCurrency(payload.bill.lateFeeAmount)}`);
  doc.moveDown();

  doc.fontSize(14).text("Charges", { underline: true });
  payload.bill.charges.forEach((charge, index) => {
    doc.fontSize(12).text(`${index + 1}. ${charge.charge_name} (${charge.charge_type || "misc"}) - ${formatCurrency(charge.amount)}`);
  });
  doc.moveDown();

  doc.fontSize(14).text("Payment Info", { underline: true });
  doc.fontSize(12).text(`Gateway Provider: ${payload.paymentInfo.gatewayProvider || "N/A"}`);
  if (payload.paymentInfo.gatewayOrderId) doc.text(`Gateway Order: ${payload.paymentInfo.gatewayOrderId}`);
  if (payload.paymentInfo.gatewayPaymentId) doc.text(`Payment ID: ${payload.paymentInfo.gatewayPaymentId}`);
  if (payload.paymentInfo.upiReference) doc.text(`UPI Reference: ${payload.paymentInfo.upiReference}`);
  if (payload.paymentInfo.paidAt) doc.text(`Paid At: ${payload.paymentInfo.paidAt}`);
  doc.moveDown();

  doc.fontSize(10).fillColor("gray").text("Thank you for your prompt payment.", { align: "center" });
  doc.moveDown();
  doc.fontSize(8).fillColor("#94a3b8").text("Generated by Nexora Society Management Platform", { align: "center" });
}

async function exportBillingReport(req, res) {
  try {
    const societyId = req.user?.societyId || req.user?.society_id || null;
    const search = req.query.search ? String(req.query.search).trim() : "";
    const status = req.query.status ? String(req.query.status).trim() : "";
    const billType = req.query.billType ? String(req.query.billType).trim() : "";
    const paymentStatus = req.query.paymentStatus ? String(req.query.paymentStatus).trim() : "";
    const format = String(req.query.format || "json").toLowerCase();

    const bills = await billModel.getBillsForAdmin({ search, status, billType, paymentStatus, societyId });
    const charges = await billModel.getChargesByBillIds(bills.map((bill) => bill.id));
    const rows = groupChargesByBillId(bills, charges);

    if (format === "csv") {
      const csvLines = [
        ["Invoice", "Resident", "Flat", "Type", "Status", "Payment Status", "Total", "Paid", "Balance", "Due Date", "Created At"].join(","),
      ];
      for (const bill of rows) {
        csvLines.push(
          [
            bill.invoice_number,
            bill.resident_name,
            bill.flat_number || "",
            bill.bill_type,
            bill.status,
            bill.payment_status,
            bill.total_amount,
            bill.paid_amount,
            bill.total_amount - bill.paid_amount,
            bill.due_date,
            bill.created_at,
          ].map((value) => `"${String(value || "").replace(/"/g, '""')}"`).join(",")
        );
      }
      res.setHeader("Content-Type", "text/csv");
      res.setHeader("Content-Disposition", "attachment; filename=billing-report.csv");
      return res.send(csvLines.join("\n"));
    }

    if (format === "excel") {
      const workbook = new ExcelJS.Workbook();
      const sheet = workbook.addWorksheet("Billing Report");
      sheet.columns = [
        { header: "Invoice", key: "invoice", width: 20 },
        { header: "Resident", key: "resident", width: 25 },
        { header: "Flat", key: "flat", width: 12 },
        { header: "Type", key: "type", width: 16 },
        { header: "Status", key: "status", width: 16 },
        { header: "Payment Status", key: "paymentStatus", width: 16 },
        { header: "Total", key: "total", width: 16 },
        { header: "Paid", key: "paid", width: 16 },
        { header: "Balance", key: "balance", width: 16 },
        { header: "Due Date", key: "dueDate", width: 16 },
        { header: "Created At", key: "createdAt", width: 20 },
      ];

      rows.forEach((bill) => {
        sheet.addRow({
          invoice: bill.invoice_number,
          resident: bill.resident_name,
          flat: bill.flat_number || "",
          type: bill.bill_type,
          status: bill.status,
          paymentStatus: bill.payment_status,
          total: Number(bill.total_amount || 0),
          paid: Number(bill.paid_amount || 0),
          balance: Number(bill.total_amount || 0) - Number(bill.paid_amount || 0),
          dueDate: bill.due_date || "",
          createdAt: bill.created_at || "",
        });
      });

      res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
      res.setHeader("Content-Disposition", "attachment; filename=billing-report.xlsx");
      await workbook.xlsx.write(res);
      return res.end();
    }

    return res.json({ success: true, data: rows });
  } catch (_error) {
    return res.status(500).json({ success: false, message: "Internal server error" });
  }
}

async function createBill(req, res) {
  try {
    // CRITICAL: Society access validation
    if (!req.user?.societyId) {
      return res.status(403).json({ success: false, message: "Society context required" });
    }

    const {
      residentId,
      title,
      dueDate,
      billingMonth = null,
      billType = "maintenance",
      charges = [],
      notes = null,
    } = req.body;

    if (!residentId || !title || !dueDate || !Array.isArray(charges) || !charges.length) {
      return res.status(400).json({
        success: false,
        message: "residentId, title, dueDate and at least one charge are required",
      });
    }

    // Basic charge validation
    for (const charge of charges) {
      if (!charge.charge_name || Number(charge.amount) <= 0) {
        return res.status(400).json({ success: false, message: "Each charge must include charge_name and amount > 0" });
      }
    }

    const resident = await userModel.getUserById(residentId);
    if (!resident || resident.role !== "resident") {
      return res.status(404).json({ success: false, message: "Resident not found" });
    }

    // Ensure resident belongs to same society as current user (or super_admin bypass)
    if (req.user.role !== "super_admin") {
      if (!resident.society_id || resident.society_id !== req.user.societyId) {
        return res.status(403).json({ success: false, message: "Cannot create bill for resident in different society" });
      }
    }

    const billId = await billModel.createBillWithCharges({
      residentId,
      societyId: resident.society_id || req.user.societyId || null,
      builderId: resident.builder_id || req.user.builder_id || null,
      title,
      dueDate,
      billingMonth,
      billType,
      notes,
      charges,
      createdBy: req.user.id,
    });

    const bill = await billModel.getBillById(billId);

    return res.status(201).json({ success: true, message: "Bill created successfully", data: bill });
  } catch (error) {
    console.error("createBill error:", error?.message || error);
    return res.status(500).json({ success: false, message: "Internal server error" });
  }
}

async function createAutoInvoices(req, res) {
  try {
    const societyId = req.user?.societyId || req.user?.society_id || null;
    const {
      residentIds = [],
      title,
      dueDate,
      billingMonth = null,
      billType = "maintenance",
      charges = [],
    } = req.body;

    if (!Array.isArray(residentIds) || !residentIds.length || !title || !dueDate || !charges.length) {
      return res.status(400).json({
        success: false,
        message: "residentIds, title, dueDate, and charges are required",
      });
    }

    const sanitizedResidentIds = residentIds.map(Number).filter(Boolean);
    const residents = await Promise.all(sanitizedResidentIds.map((id) => userModel.getUserById(id)));
    const scopedResidentIds = residents
      .filter((resident) => resident && resident.role === "resident" && (!societyId || resident.society_id === societyId))
      .map((resident) => resident.id);

    if (!scopedResidentIds.length) {
      return res.status(400).json({ success: false, message: "No valid residents found in current society" });
    }

    const created = await billModel.createAutoInvoices({
      residentIds: scopedResidentIds,
      societyId,
      billType,
      dueDate,
      billingMonth,
      title,
      chargeTemplate: charges,
      createdBy: req.user.id,
    });

    return res.status(201).json({
      success: true,
      message: "Auto invoices generated",
      data: {
        billIds: created,
        count: created.length,
      },
    });
  } catch (_error) {
    return res.status(500).json({ success: false, message: "Internal server error" });
  }
}

async function createBillTemplate(req, res) {
  try {
    const societyId = req.user?.societyId || req.user?.society_id || null;
    if (!societyId) {
      return res.status(403).json({ success: false, message: "Society context required" });
    }

    const {
      name,
      description = null,
      amount,
      dueDate,
      billingPeriod = "monthly",
      billType = "maintenance",
      gracePeriodDays = 0,
      lateFeeFixedAmount = 0,
      lateFeePercentage = 0,
      targetType = "society",
      wing = null,
      floor = null,
      flatIds = [],
    } = req.body || {};

    if (!name || !dueDate || Number(amount) <= 0) {
      return res.status(400).json({
        success: false,
        message: "Bill name, amount, and due date are required",
      });
    }

    const normalizedTargetType = ["society", "wing", "floor", "custom"].includes(targetType)
      ? targetType
      : "society";

    if (normalizedTargetType === "wing" && !String(wing || "").trim()) {
      return res.status(400).json({ success: false, message: "Wing is required for wing-wise bills" });
    }

    if (normalizedTargetType === "floor" && !String(floor || "").trim()) {
      return res.status(400).json({ success: false, message: "Floor is required for floor-wise bills" });
    }

    if (normalizedTargetType === "custom" && (!Array.isArray(flatIds) || !flatIds.length)) {
      return res.status(400).json({ success: false, message: "At least one flat is required for custom bills" });
    }

    const targets = await billModel.getBillTargets({
      societyId,
      targetType: normalizedTargetType,
      wing,
      floor,
      flatIds,
    });

    if (!targets.length) {
      return res.status(400).json({
        success: false,
        message: "No active resident flats matched the selected target",
      });
    }

    const targetValue = normalizedTargetType === "wing"
      ? { wing }
      : normalizedTargetType === "floor"
        ? { floor }
        : normalizedTargetType === "custom"
          ? { flatIds }
          : { scope: "all" };

    const templateId = await billModel.createBillTemplate({
      societyId,
      name,
      description,
      billType,
      amount: Number(amount),
      dueDate,
      billingPeriod,
      gracePeriodDays,
      lateFeeFixedAmount,
      lateFeePercentage,
      targetType: normalizedTargetType,
      targetValue,
      createdBy: req.user.id,
    });

    const billIds = await billModel.createBillsFromTemplate({
      societyId,
      builderId: req.user?.builder_id || null,
      templateId,
      targets,
      title: name,
      description,
      dueDate,
      billingMonth: req.body?.billingMonth || null,
      billType,
      amount: Number(amount),
      lateFeeFixedAmount,
      lateFeePercentage,
      gracePeriodDays,
      createdBy: req.user.id,
    });

    return res.status(201).json({
      success: true,
      message: "Billing template created and bills generated",
      data: {
        templateId,
        billIds,
        generatedCount: billIds.length,
        targetCount: targets.length,
      },
    });
  } catch (error) {
    console.error("createBillTemplate error:", error?.message || error);
    return res.status(500).json({ success: false, message: "Internal server error" });
  }
}

async function getAllBills(req, res) {
  try {
    const societyId = req.user?.societyId || req.user?.society_id || null;
    const search = req.query.search ? String(req.query.search).trim() : "";
    const status = req.query.status ? String(req.query.status).trim() : "";
    const billType = req.query.billType ? String(req.query.billType).trim() : "";
    const paymentStatus = req.query.paymentStatus ? String(req.query.paymentStatus).trim() : "";
    const wing = req.query.wing ? String(req.query.wing).trim() : "";
    const floor = req.query.floor ? String(req.query.floor).trim() : "";

    const bills = await billModel.getBillsForAdmin({ search, status, billType, paymentStatus, societyId });
    const filteredBills = bills.filter((bill) => {
      if (wing && String(bill.wing || "").toLowerCase() !== wing.toLowerCase()) return false;
      if (floor && String(bill.floor || "") !== floor) return false;
      return true;
    });
    const charges = await billModel.getChargesByBillIds(filteredBills.map((bill) => bill.id));

    return res.json({
      success: true,
      data: groupChargesByBillId(filteredBills, charges),
    });
  } catch (_error) {
    return res.status(500).json({ success: false, message: "Internal server error" });
  }
}

async function getMyBills(req, res) {
  try {
    const search = req.query.search ? String(req.query.search).trim() : "";
    const status = req.query.status ? String(req.query.status).trim() : "";
    const billType = req.query.billType ? String(req.query.billType).trim() : "";
    const paymentStatus = req.query.paymentStatus ? String(req.query.paymentStatus).trim() : "";

    const bills = await billModel.getBillsForResident(req.user.id, {
      search,
      status,
      billType,
      paymentStatus,
    });
    const charges = await billModel.getChargesByBillIds(bills.map((bill) => bill.id));

    return res.json({
      success: true,
      data: groupChargesByBillId(bills, charges),
    });
  } catch (_error) {
    return res.status(500).json({ success: false, message: "Internal server error" });
  }
}

async function getMyPaymentPortal(req, res) {
  try {
    const portalData = await billModel.getResidentPaymentPortal(req.user.id);
    return res.json({
      success: true,
      data: portalData,
    });
  } catch (_error) {
    return res.status(500).json({ success: false, message: "Internal server error" });
  }
}

async function markMyBillPaid(req, res) {
  try {
    const billId = Number(req.params.id);

    if (!billId) {
      return res.status(400).json({
        success: false,
        message: "Valid bill id is required",
      });
    }

    const myBills = await billModel.getBillsForResident(req.user.id);
    const selectedBill = myBills.find((bill) => bill.id === billId);

    if (!selectedBill) {
      return res.status(404).json({
        success: false,
        message: "Bill not found for this resident",
      });
    }

    if (selectedBill.status === "paid") {
      return res.status(400).json({
        success: false,
        message: "Bill is already paid",
      });
    }

    await billModel.markBillPaid(billId);
    const updatedBill = await billModel.getBillById(billId);

    return res.json({
      success: true,
      message: "Bill marked as paid",
      data: updatedBill,
    });
  } catch (_error) {
    return res.status(500).json({ success: false, message: "Internal server error" });
  }
}

async function createPaymentOrder(req, res) {
  try {
    const billId = Number(req.params.id);
    const method = String(req.body?.method || "upi").toLowerCase();
    const gatewayProvider = method === "razorpay" ? "razorpay" : "upi";

    const myBills = await billModel.getBillsForResident(req.user.id);
    const bill = myBills.find((row) => row.id === billId);

    if (!bill) {
      return res.status(404).json({ success: false, message: "Bill not found" });
    }

    const balanceAmount = Number(bill.total_amount || 0) - Number(bill.paid_amount || 0);
    if (balanceAmount <= 0) {
      return res.status(400).json({ success: false, message: "Bill already settled" });
    }

    const amount = Number(req.body?.amount || balanceAmount);
    if (amount <= 0 || amount > balanceAmount) {
      return res.status(400).json({ success: false, message: "Invalid payment amount" });
    }

    let razorpayOrderId = null;
    if (gatewayProvider === "razorpay" && process.env.RAZORPAY_KEY_ID && process.env.RAZORPAY_KEY_SECRET) {
      try {
        const basicToken = Buffer.from(`${process.env.RAZORPAY_KEY_ID}:${process.env.RAZORPAY_KEY_SECRET}`).toString("base64");
        const response = await fetch("https://api.razorpay.com/v1/orders", {
          method: "POST",
          headers: {
            Authorization: `Basic ${basicToken}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            amount: Math.round(amount * 100),
            currency: "INR",
            receipt: `bill_${billId}_${Date.now()}`,
            notes: {
              billId,
              residentId: req.user.id,
            },
          }),
        });

        if (response.ok) {
          const payload = await response.json();
          razorpayOrderId = payload.id;
        }
      } catch (_error) {
        razorpayOrderId = null;
      }
    }

    const order = await billModel.createPaymentOrder({
      billId,
      residentId: req.user.id,
      amount,
      paymentMethod: method,
      gatewayProvider,
      gatewayOrderId: razorpayOrderId,
      metadata: {
        upiId: req.body?.upiId || null,
      },
    });

    return res.status(201).json({
      success: true,
      message: "Payment order created",
      data: {
        paymentId: order.id,
        gatewayOrderId: order.gatewayOrderId,
        amount,
        currency: "INR",
        razorpayKeyId: process.env.RAZORPAY_KEY_ID || null,
        gatewayMode: razorpayOrderId ? "live" : "internal-fallback",
      },
    });
  } catch (_error) {
    return res.status(500).json({ success: false, message: "Internal server error" });
  }
}

async function verifyRazorpayPayment(req, res) {
  try {
    const billId = Number(req.params.id);
    const {
      paymentId,
      razorpayOrderId,
      razorpayPaymentId,
      razorpaySignature,
    } = req.body || {};

    if (!paymentId || !razorpayOrderId || !razorpayPaymentId || !razorpaySignature) {
      return res.status(400).json({ success: false, message: "Payment verification payload is incomplete" });
    }

    const payment = await billModel.getPaymentByOrderId(razorpayOrderId);
    if (!payment || Number(payment.id) !== Number(paymentId) || Number(payment.bill_id) !== billId) {
      return res.status(404).json({ success: false, message: "Payment order not found" });
    }

    if (!process.env.RAZORPAY_KEY_SECRET) {
      return res.status(400).json({ success: false, message: "Razorpay key secret is not configured" });
    }

    const digest = crypto
      .createHmac("sha256", process.env.RAZORPAY_KEY_SECRET)
      .update(`${razorpayOrderId}|${razorpayPaymentId}`)
      .digest("hex");

    if (digest !== razorpaySignature) {
      await billModel.capturePayment({
        paymentId,
        gatewayPaymentId: razorpayPaymentId,
        gatewaySignature: razorpaySignature,
        status: "failed",
      });

      return res.status(400).json({ success: false, message: "Invalid Razorpay signature" });
    }

    const updatedBill = await billModel.capturePayment({
      paymentId,
      gatewayPaymentId: razorpayPaymentId,
      gatewaySignature: razorpaySignature,
      status: "captured",
      metadata: {
        verifiedBy: "razorpay_signature",
      },
    });

    return res.json({
      success: true,
      message: "Payment verified and captured",
      data: updatedBill,
    });
  } catch (_error) {
    return res.status(500).json({ success: false, message: "Internal server error" });
  }
}

async function payViaUpi(req, res) {
  try {
    const billId = Number(req.params.id);
    const { paymentId, upiReference, upiId } = req.body || {};

    if (!paymentId || !upiReference) {
      return res.status(400).json({ success: false, message: "paymentId and upiReference are required" });
    }

    const updatedBill = await billModel.capturePayment({
      paymentId,
      upiReference,
      status: "captured",
      metadata: {
        paymentMethod: "upi",
        upiId: upiId || null,
      },
    });

    if (!updatedBill || Number(updatedBill.id) !== billId) {
      return res.status(404).json({ success: false, message: "Bill payment not found" });
    }

    return res.json({
      success: true,
      message: "UPI payment recorded",
      data: updatedBill,
    });
  } catch (_error) {
    return res.status(500).json({ success: false, message: "Internal server error" });
  }
}

async function generateInvoice(req, res) {
  try {
    const billId = Number(req.params.id);
    const bill = await billModel.getBillById(billId);

    if (!bill) {
      return res.status(404).json({ success: false, message: "Bill not found" });
    }

    if (![bill.resident_id, bill.created_by].includes(Number(req.user.id)) && !["admin", "secretary", "super_admin"].includes(req.user.role)) {
      return res.status(403).json({ success: false, message: "Not allowed" });
    }

    return res.json({
      success: true,
      data: buildInvoicePayload(bill),
    });
  } catch (_error) {
    return res.status(500).json({ success: false, message: "Internal server error" });
  }
}

async function downloadInvoicePdf(req, res) {
  try {
    const billId = Number(req.params.id);
    const bill = await billModel.getBillById(billId);

    if (!bill) {
      return res.status(404).json({ success: false, message: "Bill not found" });
    }

    if (![bill.resident_id, bill.created_by].includes(Number(req.user.id)) && !["admin", "secretary", "super_admin"].includes(req.user.role)) {
      return res.status(403).json({ success: false, message: "Not allowed" });
    }

    const payload = buildInvoicePayload(bill);
    const filename = `invoice-${payload.invoiceNumber || bill.id}.pdf`;
    streamPdfResponse(res, filename, (doc) => buildInvoicePdf(doc, payload));
    return null;
  } catch (_error) {
    return res.status(500).json({ success: false, message: "Internal server error" });
  }
}

async function runLateFeeAutomation(req, res) {
  try {
    const lateFeeType = String(req.body?.lateFeeType || "percentage").toLowerCase();
    const lateFeeValue = Number(req.body?.lateFeeValue || 5);
    const graceDays = Number(req.body?.graceDays || 0);

    const result = await billModel.applyLateFeeAutomation({
      runBy: req.user.id,
      lateFeeType,
      lateFeeValue,
      graceDays,
      societyId: req.user?.societyId || req.user?.society_id || null,
    });

    return res.json({
      success: true,
      message: "Late fee automation completed",
      data: result,
    });
  } catch (_error) {
    return res.status(500).json({ success: false, message: "Internal server error" });
  }
}

async function runPaymentReminders(req, res) {
  try {
    const dueSoonDays = Number(req.body?.dueSoonDays || 3);
    const societyId = req.user?.societyId || req.user?.society_id || null;
    const pendingBills = await billModel.getBillsForAdmin({ status: "", paymentStatus: "", societyId });

    const result = await billModel.createPaymentReminders({
      createdBy: req.user.id,
      dueSoonDays,
      societyId,
    });

    for (const bill of pendingBills) {
      const billStatus = String(bill.status || "").toLowerCase();
      const paymentStatus = String(bill.payment_status || "").toLowerCase();
      if (!["unpaid", "overdue", "partially_paid"].includes(billStatus) && !["pending", "failed", "partial"].includes(paymentStatus)) {
        continue;
      }

      const dueDate = bill.due_date ? new Date(bill.due_date) : null;
      const remainingAmount = Number(bill.total_amount || 0) - Number(bill.paid_amount || 0);
      if (!dueDate || remainingAmount <= 0) {
        continue;
      }

      const now = new Date();
      const dateOnlyNow = new Date(now.toISOString().slice(0, 10));
      const isOverdue = dueDate < dateOnlyNow;
      const dueSoonDate = new Date(dateOnlyNow);
      dueSoonDate.setDate(dueSoonDate.getDate() + dueSoonDays);
      if (!isOverdue && dueDate > dueSoonDate) {
        continue;
      }

      await notificationModel.createNotification({
        targetRole: "resident",
        targetUserId: bill.resident_id,
        title: isOverdue ? "Overdue maintenance payment" : "Upcoming maintenance payment",
        message: isOverdue
          ? `Your bill ${bill.invoice_number || bill.id} is overdue. Pending amount: INR ${remainingAmount.toFixed(2)}.`
          : `Your bill ${bill.invoice_number || bill.id} is due soon. Pending amount: INR ${remainingAmount.toFixed(2)}.`,
        priority: isOverdue ? "high" : "medium",
        category: "payment_reminder",
        relatedType: "bill",
        relatedId: bill.id,
        deepLink: `/billing/${bill.id}`,
      });
    }

    return res.json({
      success: true,
      message: "Payment reminders processed",
      data: result,
    });
  } catch (_error) {
    return res.status(500).json({ success: false, message: "Internal server error" });
  }
}

async function getBillingDashboard(req, res) {
  try {
    const dashboard = await billModel.getBillingDashboard({
      societyId: req.user?.societyId || req.user?.society_id || null,
    });
    return res.json({ success: true, data: dashboard });
  } catch (_error) {
    return res.status(500).json({ success: false, message: "Internal server error" });
  }
}

async function getFinancialAnalytics(req, res) {
  try {
    const analyticsData = await billModel.getFinancialAnalyticsData({
      societyId: req.user?.societyId || req.user?.society_id || null,
    });

    let aiInsights = null;
    try {
      const aiStats = await generateAnalytics({ societyId: req.user?.societyId || req.user?.society_id || null });
      const collectionRate = analyticsData.collectionEfficiency.at(-1)?.collectionRate || 0;
      const highRiskDefaulters = analyticsData.defaulters.filter((item) => Number(item.outstandingAmount) > 5000).length;

      aiInsights = {
        summary: `Collection rate is ${collectionRate}%. High-risk defaulters detected: ${highRiskDefaulters}.`,
        recommendations: [
          "Schedule reminder campaigns 3 days before due date and on due date.",
          "Apply dynamic late fee slabs for repeat defaulters.",
          "Offer UPI-first one-click payment links for faster conversion.",
        ],
        aiContext: aiStats,
      };
    } catch (_error) {
      aiInsights = {
        summary: "AI insight generation is currently unavailable.",
        recommendations: [],
      };
    }

    return res.json({
      success: true,
      data: {
        ...analyticsData,
        aiInsights,
      },
    });
  } catch (_error) {
    return res.status(500).json({ success: false, message: "Internal server error" });
  }
}

module.exports = {
  createBill,
  createAutoInvoices,
  createBillTemplate,
  getAllBills,
  getMyBills,
  getMyPaymentPortal,
  markMyBillPaid,
  createPaymentOrder,
  verifyRazorpayPayment,
  payViaUpi,
  generateInvoice,
  downloadInvoicePdf,
  exportBillingReport,
  runLateFeeAutomation,
  runPaymentReminders,
  getBillingDashboard,
  getFinancialAnalytics,
};
