-- Chairman and Super Admin dashboard safety sync.
-- Safe for Supabase PostgreSQL: no data deletion, only missing tables/columns/indexes.

CREATE TABLE IF NOT EXISTS societies (
  id SERIAL PRIMARY KEY,
  name TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE societies ADD COLUMN IF NOT EXISTS society_name TEXT;
ALTER TABLE societies ADD COLUMN IF NOT EXISTS code VARCHAR(30);
ALTER TABLE societies ADD COLUMN IF NOT EXISTS slug TEXT;
ALTER TABLE societies ADD COLUMN IF NOT EXISTS subdomain TEXT;
ALTER TABLE societies ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE societies ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE societies ADD COLUMN IF NOT EXISTS state TEXT;
ALTER TABLE societies ADD COLUMN IF NOT EXISTS pincode TEXT;
ALTER TABLE societies ADD COLUMN IF NOT EXISTS contact_email TEXT;
ALTER TABLE societies ADD COLUMN IF NOT EXISTS contact_phone TEXT;
ALTER TABLE societies ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'active';
ALTER TABLE societies ADD COLUMN IF NOT EXISTS subscription_plan VARCHAR(50) DEFAULT 'starter';
ALTER TABLE societies ADD COLUMN IF NOT EXISTS default_language VARCHAR(10) DEFAULT 'en';
ALTER TABLE societies ADD COLUMN IF NOT EXISTS chairman_id INTEGER;
ALTER TABLE societies ADD COLUMN IF NOT EXISTS primary_admin_user_id INTEGER;
ALTER TABLE societies ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name TEXT,
  email TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS role VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'pending';
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS society_id INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS mobile TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS user_approvals (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE user_approvals ADD COLUMN IF NOT EXISTS user_id INTEGER;
ALTER TABLE user_approvals ADD COLUMN IF NOT EXISTS society_id INTEGER;
ALTER TABLE user_approvals ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'pending';
ALTER TABLE user_approvals ADD COLUMN IF NOT EXISTS approval_type VARCHAR(80) DEFAULT 'registration';
ALTER TABLE user_approvals ADD COLUMN IF NOT EXISTS requested_by INTEGER;
ALTER TABLE user_approvals ADD COLUMN IF NOT EXISTS approved_by INTEGER;
ALTER TABLE user_approvals ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP;
ALTER TABLE user_approvals ADD COLUMN IF NOT EXISTS approval_comments TEXT;
ALTER TABLE user_approvals ADD COLUMN IF NOT EXISTS rejection_reason TEXT;
ALTER TABLE user_approvals ADD COLUMN IF NOT EXISTS documents_json JSONB;
ALTER TABLE user_approvals ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS flats (id SERIAL PRIMARY KEY, society_id INTEGER, status VARCHAR(50), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS bills (id SERIAL PRIMARY KEY, society_id INTEGER, status VARCHAR(50), total_amount NUMERIC DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS complaints (id SERIAL PRIMARY KEY, society_id INTEGER, status VARCHAR(50), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS visitors (id SERIAL PRIMARY KEY, society_id INTEGER, status VARCHAR(50), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS notices (id SERIAL PRIMARY KEY, society_id INTEGER, status VARCHAR(50), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS staff (id SERIAL PRIMARY KEY, society_id INTEGER, status VARCHAR(50), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS security (id SERIAL PRIMARY KEY, society_id INTEGER, status VARCHAR(50), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS documents (id SERIAL PRIMARY KEY, society_id INTEGER, status VARCHAR(50), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS reports (id SERIAL PRIMARY KEY, society_id INTEGER, status VARCHAR(50), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS notifications (id SERIAL PRIMARY KEY, society_id INTEGER, user_id INTEGER, status VARCHAR(50), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS audit_logs (id SERIAL PRIMARY KEY, user_id INTEGER, society_id INTEGER, action TEXT, status VARCHAR(50), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE INDEX IF NOT EXISTS idx_societies_code ON societies (code);
CREATE INDEX IF NOT EXISTS idx_societies_status ON societies (status);
CREATE INDEX IF NOT EXISTS idx_societies_chairman ON societies (chairman_id);
CREATE INDEX IF NOT EXISTS idx_users_society_role_status ON users (society_id, role, status);
CREATE INDEX IF NOT EXISTS idx_user_approvals_society_status ON user_approvals (society_id, status);
CREATE INDEX IF NOT EXISTS idx_user_approvals_type_status ON user_approvals (approval_type, status);
